#!/bin/bash


if [[ "$1" == "c" ]]; then
    if [[ "$2" == "xm5" ]]; then
        bluetoothctl connect 88:C9:E8:37:FC:92
    fi
    if [[ "$2" == "rh" ]]; then
        bluetoothctl connect 64:31:39:64:1D:D9
    fi
elif [[ "$1" == "d" ]]; then
    if [[ "$2" == "xm5" ]]; then
        bluetoothctl disconnect 88:C9:E8:37:FC:92
    fi
    if [[ "$2" == "rh" ]]; then
        bluetoothctl disconnect 64:31:39:64:1D:D9
    fi
fi
